// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBP5L-zSjshQwjNASnYZ4SH9Ou9PN0kzAQ',
    appId: '1:840739691330:web:614296709d2eedf9e2c6db',
    messagingSenderId: '840739691330',
    projectId: 'wavelinkapp-e100c',
    authDomain: 'wavelinkapp-e100c.firebaseapp.com',
    storageBucket: 'wavelinkapp-e100c.firebasestorage.app',
    measurementId: 'G-DFVKXFMEXD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNkfmbZNq1bjd3_c8WKmqANrs05f3E2W4',
    appId: '1:840739691330:android:911c884c99c2cad9e2c6db',
    messagingSenderId: '840739691330',
    projectId: 'wavelinkapp-e100c',
    storageBucket: 'wavelinkapp-e100c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkW5psb47E8-600Yb72TUJkBlZ--VJC70',
    appId: '1:840739691330:ios:56c34d9290c0de06e2c6db',
    messagingSenderId: '840739691330',
    projectId: 'wavelinkapp-e100c',
    storageBucket: 'wavelinkapp-e100c.firebasestorage.app',
    iosBundleId: 'com.example.wavelinkApp',
  );
}
